name: monorepo packages workflow

on: 
  push:
    branches: 
      - '*'
  pull_request:
    types: [opened]
    branches: ['*']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: ✅ Checkout Code
        uses: actions/checkout@v3

      - name: ✅ Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: ✅ corepack trigger
        run: corepack enable
      
      - name: ✅ Monorepo Install Dependencies
        run: yarn install --immutable --inline-builds